import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import * as uniJis2004Utf16H from "@/const/UniJIS2004-UTF16-H.json";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const uniToCid = uniJis2004Utf16H.uniToCid;
  const sortedUniToCid = uniToCid.sort((a, b) => a.cid - b.cid);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        cmap-display
        {sortedUniToCid.map((pair, index) => (
          <div key={index}>
            <div>{pair.unicode}</div>
            <div>{String.fromCharCode(pair.unicode)}</div>
            <div>{pair.cid}</div>
          </div>
        ))}
      </main>
    </>
  );
}
