import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "styled-components";
import * as uniJis2004Utf16H from "@/const/UniJIS2004-UTF16-H.json";
import { Glyph } from "@/components/Glyph";
import Link from "next/link";

const Page = styled.div`
  color: #333;
  margin: 32px 40px;
  display: flex;
`;

const Navigation = styled.nav`
  padding-left: 40px;
  position: fixed;
  left: 0;
`;

const Header = styled.header`
  display: flex;
  align-items: center;
  gap: 16px;
`;

const H1 = styled.h1`
  line-height: 1;
  font-size: 20px;
  margin: 0 0 16px 0;
`;

const H2 = styled.h2`
  margin: 0;
`;

const CmapList = styled.ul`
  margin: 0;
  padding: 0;
  list-style: none;
`;

const Main = styled.div`
  margin-left: 220px;
`;

const Glyphs = styled.div<{ bgColor: string }>`
  width: ${60 * 10 + 8 * 9}px;
  margin: 0 -16px;
  padding: 16px;
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  background: ${({ bgColor }) => bgColor};
`;

export default function Home() {
  const uniToCid = uniJis2004Utf16H.uniToCid;
  const sortedUniToCid = uniToCid.sort((a, b) => a.cid - b.cid);

  const std = sortedUniToCid.filter(({ cid }) => cid <= 9353);
  const pro = sortedUniToCid.filter(({ cid }) => 9353 < cid && cid <= 15443);
  const pr5 = sortedUniToCid.filter(({ cid }) => 15443 < cid && cid <= 20316);
  const pr6 = sortedUniToCid.filter(({ cid }) => 20316 < cid);

  const colors = {
    std: "transparent",
    pro: "hsl(40, 100%, 94%)",
    pr5: "hsl(100, 100%, 94%)",
    pr6: "hsl(160, 100%, 94%)",
  };

  return (
    <>
      <Head>
        <title>cmap-display</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <Navigation>
          <H1>cmap-display</H1>
          <h3>Adobe-Japan 1-7</h3>
          <CmapList>
            <li>
              <Link href="/UniJIS-UTF16-H">UniJIS-UTF16-H</Link>
            </li>
            <li>
              <Link href="/UniJIS-UTF16-V">UniJIS-UTF16-V</Link>
            </li>
            <li>
              <Link href="/UniJIS2004-UTF16-V">UniJIS2004-UTF16-H</Link>
            </li>
            <li>
              <Link href="/UniJIS2004-UTF16-V">UniJIS2004-UTF16-V</Link>
            </li>
          </CmapList>
          <h3>文字セット</h3>
          <ul>
            <li>
              <a href="#std">Std</a>
            </li>
            <li>
              <a href="#pro">Pro</a>
            </li>
            <li>
              <a href="#pr5">Pr5</a>
            </li>
            <li>
              <a href="#pr6">Pr6</a>
            </li>
          </ul>
        </Navigation>
        <Main>
          <Header>
            <H2>UniJIS2004-UTF16-H</H2>
            <a href="">CMap をダウンロード</a>
            <a href="">JSON 形式でダウンロード</a>
          </Header>
          <section id="std">
            <h3>Std（Adobe-Japan 1-3）</h3>
            <Glyphs bgColor={colors.std}>
              {std.map((pair, index) => (
                <Glyph unicode={pair.unicode} cid={pair.cid} key={index} />
              ))}
            </Glyphs>
          </section>
          <section id="pro">
            <h3>Pro（Adobe-Japan 1-4）</h3>
            <Glyphs bgColor={colors.pro}>
              {pro.map((pair, index) => (
                <Glyph unicode={pair.unicode} cid={pair.cid} key={index} />
              ))}
            </Glyphs>
          </section>
          <section id="pr5">
            <h3>Pr5（Adobe-Japan 1-5）</h3>
            <Glyphs bgColor={colors.pr5}>
              {pr5.map((pair, index) => (
                <Glyph unicode={pair.unicode} cid={pair.cid} key={index} />
              ))}
            </Glyphs>
          </section>
          <section id="pr6">
            <h3>Pr6（Adobe-Japan 1-6/7）</h3>
            <Glyphs bgColor={colors.pr6}>
              {pr6.map((pair, index) => (
                <Glyph unicode={pair.unicode} cid={pair.cid} key={index} />
              ))}
            </Glyphs>
          </section>
        </Main>
      </Page>
    </>
  );
}
